/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_utils_BsPatch */

#ifndef _Included_com_utils_BsPatch
#define _Included_com_utils_BsPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_utils_BsPatch
 * Method:    exbspatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_utils_BsPatch_exbspatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
